### PR TITLE
Allow passing GuzzleHttp\Client into Recombee client constructor

### PR DESCRIPTION
**Pull request by matyx**

### CODE REVIEW

**Comment by OndraFiedler** [comment]
I think it might be better to pass the Guzzle client in the `options` array along with other optional settings (under `guzzleClient` key as the keys are camelCase).

**Comment by matyx** [comment]
Okay, we have no problems with this. Will you do this, or should I send another PR?

**Comment by OndraFiedler** [comment]
@matyx Another PR would be great. Thanks!

**Comment by matyx** [comment]
Closing in favor of #28

**Pull request closed without merging**
