### PR TITLE
Remove php end tag in all files (causes whitespaces on output)

### PR DESCRIPTION
**Pull request by matyx**

### CODE REVIEW

**Comment by OndraFiedler** [comment]
@matyx Can you please describe what is the reasoning for this change?

**Comment by matyx** [comment]
Using php end tags is considered bad practise in PHP, because there are some whitespace characters, that are written to output when you include this library

**Comment by OndraFiedler** [comment]
Can you please link some documentation to support the claim?

**Comment by matyx** [comment]
https://www.php.net/basic-syntax.instruction-separation

**Pull request merged**
